// Renders agent-discoverable documentation from the CLI's own commander tree, so
// the docs can never drift from the flags the binary actually accepts. Produces:
//   - one markdown file per command under docs/ (plus docs/global-options.md)
//   - llms.txt   — the llms.txt-standard index of links
//   - llms-full.txt — every command's reference concatenated into one file
// Output is deterministic (no dates, no version) so a checked-in copy can be
// diffed in CI. Regenerate with `pnpm docs:generate`.
import type { Argument, Command, Option } from "commander";
import { GLOBAL_OPTION_LONGS, GLOBAL_OPTIONS } from "../program.js";

/** Banner stamped on every generated file so nobody hand-edits it. */
const BANNER = "<!-- Generated by `pnpm docs:generate` from the CLI definitions. Do not edit by hand. -->";

export interface RenderedDocs {
  /** Contents of `llms.txt` (the index). */
  index: string;
  /** Contents of `llms-full.txt` (everything inline). */
  full: string;
  /** Per-file contents, keyed by path relative to `docs/` (e.g. `login.md`). */
  files: Map<string, string>;
}

interface DocCommand {
  /** Path segments below the root, e.g. ["voices", "list"]. */
  path: string[];
  /** `docs/` filename, e.g. `voices-list.md`. */
  slug: string;
  command: Command;
  children: DocCommand[];
}

/** A commander-added option we never document (help/version) — filtered by long flag. */
const INTRINSIC_LONGS = new Set(["--help", "--version"]);

function isDocumentedOption(option: Option): boolean {
  if (option.hidden) return false;
  const long = option.long ?? option.short ?? "";
  if (INTRINSIC_LONGS.has(long)) return false;
  return !GLOBAL_OPTION_LONGS.has(long);
}

/** Command-specific (non-global, non-hidden) options, in declaration order. */
function ownOptions(command: Command): Option[] {
  return command.options.filter(isDocumentedOption);
}

/** Walk the commander tree into a nested list of documentable commands (root excluded). */
function collect(command: Command, parents: string[] = []): DocCommand[] {
  return (
    command.commands
      // Skip commander's implicit `help` command; everything else is ours.
      .filter((sub) => sub.name() !== "help")
      .map((sub) => {
        const path = [...parents, sub.name()];
        return {
          path,
          slug: `${path.join("-")}.md`,
          command: sub,
          children: collect(sub, path),
        };
      })
  );
}

/** Flatten the nested command list depth-first, preserving tree order. */
function flatten(nodes: DocCommand[]): DocCommand[] {
  return nodes.flatMap((node) => [node, ...flatten(node.children)]);
}

function fullName(path: string[]): string {
  return ["speechify", ...path].join(" ");
}

function argToken(arg: Argument): string {
  const name = `${arg.name()}${arg.variadic ? "..." : ""}`;
  return arg.required ? `<${name}>` : `[${name}]`;
}

function formatDefault(value: unknown): string {
  if (Array.isArray(value)) return value.map((v) => `\`${String(v)}\``).join(", ");
  return `\`${String(value)}\``;
}

/** A default worth printing: skip `undefined` and the implicit `false` of a boolean flag. */
function hasMeaningfulDefault(option: Option): boolean {
  if (option.defaultValue === undefined) return Boolean(option.defaultValueDescription);
  if (option.defaultValue === false) return false;
  if (Array.isArray(option.defaultValue) && option.defaultValue.length === 0) return false;
  return true;
}

function optionLine(option: Option): string {
  let line = `- \`${option.flags}\``;
  if (option.description) line += ` — ${option.description}`;

  const notes: string[] = [];
  if (option.mandatory) notes.push("required");
  const choices = (option as { argChoices?: string[] }).argChoices;
  if (choices?.length) notes.push(`choices: ${choices.map((c) => `\`${c}\``).join(", ")}`);
  if (hasMeaningfulDefault(option)) {
    notes.push(
      option.defaultValue === undefined && option.defaultValueDescription
        ? `default: ${option.defaultValueDescription}`
        : `default: ${formatDefault(option.defaultValue)}`,
    );
  }
  if (notes.length) line += ` (${notes.join("; ")})`;
  return line;
}

function argLine(arg: Argument): string {
  let line = `- \`${argToken(arg)}\``;
  if (arg.description) line += ` — ${arg.description}`;
  if (arg.defaultValue !== undefined) line += ` (default: ${formatDefault(arg.defaultValue)})`;
  return line;
}

/** Render a single command's markdown page (without the leading banner). */
function renderCommand(node: DocCommand): string {
  const { command, path, children } = node;
  const usageArgs = command.registeredArguments.map(argToken).join(" ");
  const opts = ownOptions(command);
  const runnable = command.registeredArguments.length > 0 || opts.length > 0 || children.length === 0;

  const lines: string[] = [`# ${fullName(path)}`, ""];
  if (command.description()) lines.push(command.description(), "");

  lines.push("## Usage", "", "```", `${fullName(path)}${usageArgs ? ` ${usageArgs}` : ""} [options]`, "```", "");

  if (command.registeredArguments.length) {
    lines.push("## Arguments", "", ...command.registeredArguments.map(argLine), "");
  }

  if (opts.length) {
    lines.push("## Options", "", ...opts.map(optionLine), "");
  }

  if (children.length) {
    lines.push("## Subcommands", "");
    for (const child of children) {
      const desc = child.command.description();
      lines.push(`- [${fullName(child.path)}](./${child.slug})${desc ? ` — ${desc}` : ""}`);
    }
    lines.push("");
  }

  if (runnable) {
    lines.push("Global options apply here too — see [global options](./global-options.md).", "");
  }

  return lines.join("\n").trimEnd();
}

function renderGlobalOptions(): string {
  const lines: string[] = [
    "# Global options",
    "",
    "These flags are accepted by every `speechify` command (and its subcommands).",
    "",
    ...GLOBAL_OPTIONS.map(([flags, description]) => `- \`${flags}\` — ${description}`),
    "",
    "Environment equivalents: `$SPEECHIFY_API_KEY` (`--api-key`), `$SPEECHIFY_BASE_URL`",
    "(`--base-url`), `$SPEECHIFY_API_VERSION` (`--api-version`). An explicit flag always",
    "wins over the environment.",
  ];
  return lines.join("\n").trimEnd();
}

function withBanner(body: string): string {
  return `${BANNER}\n\n${body}\n`;
}

/** Build every documentation artifact from a commander program. Pure + deterministic. */
export function renderDocs(program: Command): RenderedDocs {
  const tree = collect(program);
  const all = flatten(tree);
  const files = new Map<string, string>();

  files.set("global-options.md", withBanner(renderGlobalOptions()));
  for (const node of all) files.set(node.slug, withBanner(renderCommand(node)));

  const rootDescription = program.description() || "SpeechifyAI command-line companion for the Speechify API.";

  // llms.txt — the index of links (top-level commands, then reference).
  const indexLines: string[] = [
    "# Speechify CLI",
    "",
    `> ${rootDescription}`,
    "",
    "`speechify` is the command-line companion to the Speechify API — authenticate with",
    "an API key, synthesize speech, manage voices, run raw API calls, and relay a local",
    "MCP client to Speechify's hosted MCP server.",
    "",
    "## Commands",
    "",
    ...tree.map((node) => {
      const desc = node.command.description();
      return `- [${fullName(node.path)}](docs/${node.slug})${desc ? `: ${desc}` : ""}`;
    }),
    "",
    "## Reference",
    "",
    "- [Global options](docs/global-options.md): flags available on every command.",
    "- [Full reference](llms-full.txt): every command and flag in one file.",
  ];
  const index = `${indexLines.join("\n").trimEnd()}\n`;

  // llms-full.txt — everything inline, in tree order.
  const fullSections: string[] = [
    "# Speechify CLI — full reference",
    "",
    `> ${rootDescription}`,
    "",
    "Generated from the CLI definitions with `pnpm docs:generate`. Do not edit by hand.",
    "",
    "---",
    "",
    renderGlobalOptions(),
  ];
  for (const node of all) {
    fullSections.push("", "---", "", renderCommand(node));
  }
  const full = `${fullSections.join("\n").trimEnd()}\n`;

  return { index, full, files };
}
