// Generate src/generated/models.ts from the live API — GET /v1/audio/models.
//
// The `--model` choices list must reflect what the API actually serves (the SDK
// union lags it: e.g. simba-3.2 ships in the API before the SDK types know it),
// so the list is fetched from the models endpoint and written as build-time
// metadata. Wired into `pnpm build`; the output is committed so offline builds,
// typecheck, and tests keep working without a key.
//
// Usage:
//   SPEECHIFY_API_KEY=<key> node scripts/generate-models.mjs
//   SPEECHIFY_API_KEY=<key> SPEECHIFY_BASE_URL=<url> node scripts/generate-models.mjs
//
// Exit 0 on success or when the existing generated file is reused (offline
// fallback, warning printed); exit 1 if there is nothing to fall back to.
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const outPath = resolve(root, "src/generated/models.ts");
const baseUrl = (process.env.SPEECHIFY_BASE_URL || "https://api.speechify.ai").replace(/\/+$/, "");
const apiKey = process.env.SPEECHIFY_API_KEY;

async function fetchModels() {
  if (!apiKey) throw new Error("SPEECHIFY_API_KEY is not set");
  const res = await fetch(`${baseUrl}/v1/audio/models`, {
    headers: { Authorization: `Bearer ${apiKey}` },
    signal: AbortSignal.timeout(15_000),
  });
  if (!res.ok) throw new Error(`GET /v1/audio/models → HTTP ${res.status}`);
  const body = await res.json();
  const models = body?.models;
  if (!Array.isArray(models)) throw new Error("unexpected response shape: missing models[]");
  const ids = models.map((m) => m?.id).filter((id) => typeof id === "string" && id.length > 0);
  if (ids.length === 0) throw new Error("unexpected response shape: empty models[]");
  return ids;
}

function render(ids) {
  const lines = ids.map((id) => `  "${id}",`).join("\n");
  return `// Generated by scripts/generate-models.mjs from GET /v1/audio/models (${baseUrl}).
// Do not edit by hand. Regenerate with \`pnpm build\` (or run the script directly).

export const SPEECH_MODELS = [
${lines}
] as const;
`;
}

async function reuseExisting(reason) {
  try {
    const existing = await readFile(outPath, "utf8");
    console.warn(`warning: ${reason}; keeping existing ${outPath}`);
    return existing.length > 0;
  } catch {
    console.error(`error: ${reason} and ${outPath} does not exist`);
    console.error("       run: SPEECHIFY_API_KEY=<key> node scripts/generate-models.mjs");
    process.exit(1);
  }
}

try {
  const ids = await fetchModels();
  await mkdir(dirname(outPath), { recursive: true });
  await writeFile(outPath, render(ids));
  console.log(`wrote ${outPath} (${ids.length} models: ${ids.join(", ")})`);
} catch (err) {
  await reuseExisting(err.message);
}
